// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Blink Auto Detailing';
}

<main>
  <app-header></app-header>
  <app-hero></app-hero>
  <app-services></app-services>
  <app-about></app-about>
  <app-gallery></app-gallery>
  <app-reviews></app-reviews>
  <app-contact></app-contact>
  <app-footer></app-footer>
</main>

// app/page.tsx
import { Header } from "@/components/header"
import { Hero } from "@/components/hero"
import { Services } from "@/components/services"
import { About } from "@/components/about"
import Gallery from "@/components/gallery"
import { Reviews } from "@/components/reviews"
import { Contact } from "@/components/contact"
import { Footer } from "@/components/footer"

export default function Home() {
  return (
    <main className="min-h-screen">
      <Header />
      <Hero />
      <Services />
      <About />
      <Gallery />
      <Reviews />
      <Contact />
      <Footer />
    </main>
  )
}
