// src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';

interface ContactForm {
  name: string;
  email: string;
  phone: string;
  message: string;
}

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent {
  formData: ContactForm = {
    name: '',
    email: '',
    phone: '',
    message: ''
  };

  onSubmit() {
    console.log('Form submitted:', this.formData);
    alert('Thank you for your inquiry! We will get back to you soon.');
    this.formData = {
      name: '',
      email: '',
      phone: '',
      message: ''
    };
  }
}

<section id="contact" class="contact-section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Ready to Experience Excellence?</h2>
      <p class="section-description">
        Call us out today to book your detail or request a personalized quote for your vehicle.
      </p>
    </div>

    <div class="contact-grid">
      <div class="contact-card">
        <div class="card-icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
          </svg>
        </div>
        <h3>Call or Text</h3>
        <p class="card-value">(289) 682-5465</p>
        <p class="card-subtitle">Available for quotes and bookings</p>
      </div>

      <div class="contact-card">
        <div class="card-icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
            <polyline points="22,6 12,13 2,6"></polyline>
          </svg>
        </div>
        <h3>Email Us</h3>
        <p class="card-value">blinkautodetailing&#64;gmail.com</p>
        <p class="card-subtitle">We'll respond within 24 hours</p>
      </div>

      <div class="contact-card">
        <div class="card-icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
            <circle cx="12" cy="10" r="3"></circle>
          </svg>
        </div>
        <h3>Visit Us</h3>
        <p class="card-value">181 South Service Road West, Unit 2</p>
        <p class="card-subtitle">Grimsby, ON L3M 4H6<br>Proudly serving Niagara</p>
      </div>

      <div class="contact-card">
        <div class="card-icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"></circle>
            <polyline points="12 6 12 12 16 14"></polyline>
          </svg>
        </div>
        <h3>Hours</h3>
        <p class="card-value">By Appointment Only</p>
        <p class="card-subtitle">Flexible scheduling available</p>
      </div>
    </div>

    <div class="cta-button">
      <button class="btn-primary">Book Your Detail Now</button>
    </div>
  </div>
</section>

// components/contact.tsx
"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Phone, Mail, MapPin, Clock } from "lucide-react"

export function Contact() {
  return (
    <section id="contact" className="bg-background text-foreground py-24 md:py-32"> 
      {/* Decorative gradient */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-accent rounded-full blur-3xl" />
      </div>

      <div className="container mx-auto px-4 relative z-10">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2
              className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-balance"
              style={{ fontFamily: "var(--font-playfair)" }}
            >
              Ready to Experience
              <span className="text-primary"> Excellence?</span>
            </h2>
            <p className="text-lg text-muted-foreground text-pretty max-w-2xl mx-auto">
              Call or text today to book your detail or request a personalized quote for your vehicle.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 mb-12">
            {/* Contact Info Cards */}
            <Card className="bg-card border-border">
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <Phone className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg mb-2">Call or Text</h3>
                    <a  href="tel:2896825465" className="text-lg text-primary hover:text-primary/80 transition-colors">
                      (289) 682-5465
                      </a>

                    <p className="text-sm text-muted-foreground mt-2">Available for quotes and bookings</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card border-border">
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                    <Mail className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg mb-2">Email Us</h3>
                    <a
                      href="mailto:blinkautodetailing@gmail.com"
                      className="text-lg text-primary hover:text-primary/80 transition-colors break-all"
                    >
                      blinkautodetailing@gmail.com
                    </a>
                    <p className="text-sm text-muted-foreground mt-2">We'll respond within 24 hours</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card border-border">
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                    <MapPin className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg mb-2">Visit Us</h3>
                    <p className="text-foreground">
                      181 South Service Road West, Unit 2
                      <br />
                      Grimsby, ON L3M 4H6
                    </p>
                    <p className="text-sm text-muted-foreground mt-2">Proudly serving Niagara</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card border-border">
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div className="h-12 w-12 rounded-lg bg-accent/10 flex items-center justify-center flex-shrink-0">
                    <Clock className="h-6 w-6 text-accent" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg mb-2">Hours</h3>
                    <p className="text-foreground">By Appointment Only</p>
                    <p className="text-sm text-muted-foreground mt-2">Flexible scheduling available</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* CTA */}
          <div className="text-center">
            <a href="tel:2896825465">
              <Button
                size="lg"
                className="bg-accent text-accent-foreground hover:bg-accent/90 font-semibold text-lg px-12 h-14"
              >
                <Phone className="mr-2 h-5 w-5" />
                Book Your Detail Now
              </Button>
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}
