// src/app/components/reviews/reviews.component.ts
import { Component } from '@angular/core';

interface Review {
  author: string;
  rating: number;
  text: string;
  date: string;
}

@Component({
  selector: 'app-reviews',
  templateUrl: './reviews.component.html',
  styleUrls: ['./reviews.component.css']
})
export class ReviewsComponent {
  reviews: Review[] = [
    {
      author: 'Michael S.',
      rating: 5,
      text: 'Exceptional attention to detail. They transformed my car and it looks better than when I bought it. The Graphene coating is simply outstanding.',
      date: 'December 2024'
    },
    {
      author: 'Sarah T.',
      rating: 5,
      text: 'I had been trying to find someone who could handle my Bentley, and Blink exceeded all expectations. Truly premium service for luxury vehicles.',
      date: 'November 2024'
    },
    {
      author: 'David M.',
      rating: 5,
      text: 'Outstanding service from start to finish. They treat every car like it\'s their own. Highly recommend!',
      date: 'October 2024'
    },
    {
      author: 'Jennifer W.',
      rating: 5,
      text: 'The best auto detailing in Niagara. No question. Worth every penny and then some.',
      date: 'September 2024'
    }
  ];

  getRatingArray(rating: number): number[] {
    return Array(rating).fill(0);
  }
}


<section id="reviews" class="reviews-section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Trusted by Luxury Vehicle Owners</h2>
      <p class="section-description">
        Don't just take our word for it—hear from our satisfied clients who trust us with their prized vehicles.
      </p>
    </div>

    <div class="reviews-grid">
      <div *ngFor="let review of reviews" class="review-card">
        <div class="rating">
          <span *ngFor="let star of getRatingArray(review.rating)" class="star">★</span>
        </div>
        <p class="review-text">{{ review.text }}</p>
        <div class="review-footer">
          <p class="review-author">{{ review.author }}</p>
          <p class="review-date">{{ review.date }}</p>
        </div>
      </div>
    </div>

<div class="review-cta">
      <a href="https://www.google.com/search?sca_esv=f736710e6b71d7f5&sxsrf=ANbL-n6PZRUbCjEBSYlDaQ5S1gnWgIb7_g:1771043071668&si=AL3DRZEsmMGCryMMFSHJ3StBhOdZ2-6yYkXd_doETEE1OR-qOdwDCPUiDfVgf8VTqRj8zexnto5007tylps3Z5I4PcU2gOfEVGNnm0dIwgd-_JNDi7Aop3HJoBP1jHD2XfP8OtiXSyBXAsjVOSpZ2j7Mux4fmB58-Q%3D%3D&q=BLINK+Auto+Detailing+Reviews&sa=X&ved=2ahUKEwjCuKzJkdiSAxW5MtAFHSYIBHcQ0bkNegQIJRAF&biw=1745&bih=901&dpr=1.1" target="_blank" class="google-reviews-link">
        <svg class="star-icon" viewBox="0 0 24 24" fill="currentColor">
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
        </svg>
        40+ Five-Star Google Reviews
      </a>
    </div>
  </div>
</section>

// components/reviews.tsx
import { Card, CardContent } from "@/components/ui/card"
import { Star, Quote } from "lucide-react"

const reviews = [
  {
    name: "Michael R.",
    rating: 5,
    text: "Absolutely phenomenal work on my Porsche 911. The Graphene coating is incredible - water just beads right off. Best detailing service in Niagara, hands down.",
    vehicle: "Porsche 911",
  },
  {
    name: "Sarah L.",
    rating: 5,
    text: "I was blown away by the attention to detail. My Mercedes looks better than the day I bought it. The team at Blink truly cares about their craft.",
    vehicle: "Mercedes-Benz S-Class",
  },
  {
    name: "David K.",
    rating: 5,
    text: "Professional, meticulous, and worth every penny. They treated my BMW like it was their own. The ceramic coating has held up beautifully for over a year.",
    vehicle: "BMW M5",
  },
  {
    name: "Jennifer M.",
    rating: 5,
    text: "Outstanding service from start to finish. The interior detailing was incredible - removed stains I thought were permanent. Highly recommend!",
    vehicle: "Range Rover Sport",
  },
]

export function Reviews() {
  return (
    <section id="reviews" className="py-24 md:py-32 bg-card">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2
            className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-balance"
            style={{ fontFamily: "var(--font-playfair)" }}
          >
            Trusted by Luxury
            <span className="text-primary"> Vehicle Owners</span>
          </h2>
          <p className="text-lg text-muted-foreground text-pretty">
            Don't just take our word for it - see what our clients have to say about their experience.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6 max-w-6xl mx-auto">
          {reviews.map((review, index) => (
            <Card
              key={index}
              className="bg-background border-border hover:border-primary/50 transition-all duration-300"
            >
              <CardContent className="pt-6">
                <div className="flex items-center gap-1 mb-4">
                  {[...Array(review.rating)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-accent text-accent" />
                  ))}
                </div>
                <Quote className="h-8 w-8 text-primary/20 mb-3" />
                <p className="text-foreground mb-4 leading-relaxed">{review.text}</p>
                <div className="flex items-center justify-between pt-4 border-t border-border">
                  <div>
                    <p className="font-semibold text-foreground">{review.name}</p>
                    <p className="text-sm text-muted-foreground">{review.vehicle}</p>
                  </div>
                  <div className="text-xs text-muted-foreground">Verified Client</div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-muted-foreground mb-2">See all our reviews on Google</p>
          <a
            href="https://www.google.com/search?q=blink+auto+detailing+grimsby"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors font-medium"
          >
            <Star className="h-4 w-4 fill-accent text-accent" />
            40+ Five-Star Google Reviews
          </a>
        </div>
      </div>
    </section>
  )
}
